### ISSUE TITLE
`Invalid count value` error when formatting

### ISSUE THREAD

**Issue by stevebeauge** [DotJoshJohnson/vscode-xml#274]
#### Description
When I try to format a large Xml file, I get error `Invalid Count Value`.

Same as #257, but the other issue has been closed (and not reopened even though other users requested to reopen)

#### Formatter Implementation
I use the V2, but using the classic implementation, the error also occurs

#### XML Tools Version
2.4.0

#### VS Code Version
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32

#### Operating System
OS: Windows_NT x64 10.0.17763 (Windows 10)

#### Stack trace in log file :

````
[2019-05-07 10:43:04.807] [exthost] [error] [DotJoshJohnson.xml] provider FAILED
[2019-05-07 10:43:04.809] [exthost] [error] RangeError: Invalid count value
	at String.repeat (<anonymous>)
	at V2XmlFormatter._getIndent (C:\Users\steve\.vscode\extensions\dotjoshjohnson.xml-2.4.0\out\formatting\formatters\v2-xml-formatter.js:206:106)
	at V2XmlFormatter.formatXml (C:\Users\steve\.vscode\extensions\dotjoshjohnson.xml-2.4.0\out\formatting\formatters\v2-xml-formatter.js:171:57)
	at XmlFormattingEditProvider.provideDocumentRangeFormattingEdits (C:\Users\steve\.vscode\extensions\dotjoshjohnson.xml-2.4.0\out\formatting\xml-formatting-edit-provider.js:39:41)
	at XmlFormattingEditProvider.provideDocumentFormattingEdits (C:\Users\steve\.vscode\extensions\dotjoshjohnson.xml-2.4.0\out\formatting\xml-formatting-edit-provider.js:12:21)
	at define.provideDocumentFormattingEdits.a.asPromise (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:589:78)
	at t.asPromise.Promise (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:49:430)
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:49:402)
	at I.provideDocumentFormattingEdits (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:589:49)
	at define.$provideDocumentFormattingEdits._withAdapter.e (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:604:633)
	at B._withAdapter (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:599:159)
	at B.$provideDocumentFormattingEdits (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:604:611)
	at d._doInvokeHandler (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:622:11)
	at d._invokeHandler (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:716)
	at d._receiveRequest (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:341)
	at d._receiveOneMessage (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:617:400)
	at u.fire (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at e (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:40:460)
	at u.fire (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at a (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:467)
	at e (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:513)
	at u.fire (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at y._receiveMessage (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:415)
	at u.fire (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at f.acceptChunk (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:174:410)
	at Socket.t (c:\Users\steve\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)

````

**Comment by DotJoshJohnson** [comment]
Closing in favor of #257. Thanks!

**Comment by UndPat** [comment]
Same problem here on version 2.5.0

VS Code
Version: 1.36.1 (user setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763


Stack trace:
`[2019-08-07 15:23:31.036] [exthost] [error] [DotJoshJohnson.xml] provider FAILED
[2019-08-07 15:23:31.036] [exthost] [error] RangeError: Invalid count value
	at String.repeat (<anonymous>)
	at V2XmlFormatter._getIndent (C:\Users\Infogen\.vscode\extensions\dotjoshjohnson.xml-2.5.0\out\formatting\formatters\v2-xml-formatter.js:208:106)
	at V2XmlFormatter.formatXml (C:\Users\Infogen\.vscode\extensions\dotjoshjohnson.xml-2.5.0\out\formatting\formatters\v2-xml-formatter.js:173:57)
	at XmlFormattingEditProvider.provideDocumentRangeFormattingEdits (C:\Users\Infogen\.vscode\extensions\dotjoshjohnson.xml-2.5.0\out\formatting\xml-formatting-edit-provider.js:39:41)
	at XmlFormattingEditProvider.provideDocumentFormattingEdits (C:\Users\Infogen\.vscode\extensions\dotjoshjohnson.xml-2.5.0\out\formatting\xml-formatting-edit-provider.js:12:21)
	at define.provideDocumentFormattingEdits.o.asPromise (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:550:168)
	at t.asPromise.Promise (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:53:995)
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:53:967)
	at P.provideDocumentFormattingEdits (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:550:139)
	at define.$provideDocumentFormattingEdits._withAdapter.e (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:565:230)
	at W._withAdapter (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:560:499)
	at W.$provideDocumentFormattingEdits (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:565:208)
	at d._doInvokeHandler (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:653:1006)
	at d._invokeHandler (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:653:698)
	at d._receiveRequest (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:652:293)
	at d._receiveOneMessage (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:651:141)
	at define.constructor._protocol.onMessage.e (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:649:400)
	at u.fire (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:468)
	at a (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:177:627)
	at e (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:177:673)
	at u.fire (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:468)
	at n.constructor.e.onMessage.e (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:758:621)
	at u.fire (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:468)
	at a (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:177:627)
	at e (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:177:673)
	at u.fire (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:468)
	at y._receiveMessage (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:186:545)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:183:860)
	at u.fire (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:48:468)
	at f.acceptChunk (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:180:393)
	at define.constructor._register._socket.onData.e (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:179:731)
	at Socket.t (c:\Users\Infogen\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:22)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)`

**Comment by stevebeauge** [comment]
@UndPat : to workaround the problem, I installed another extension : [XML Format](https://github.com/mikeburgh/vscode-xml-format). Now that VSCode supports to select the formatter for each language, you can install side by side the two extensions, and use this one just to format the xml.
